### ISSUE TITLE
Weird behaviour with parsing escapes in lines

### ISSUE THREAD

**Issue by deprilula28** [bnoazx005/tcpp#12]
tcpp will parse lines that have escapes, such as \p, even though there is no # at the beginning.

Example:
```
Line above

// "\p"
Line below
float getNumber() {
    return 1.0;
}
```

Gets turned into:
```
Line above

Line below
float getNumber() {
 return 1.0;
}
```

**Comment by bnoazx005** [comment]
@deprilula28 I've fixed the issue. Please check this out. The original problem was with parsing of backslash that was wronly recognized as line concatenation command
