### ISSUE TITLE
Conditions do not work at all

### ISSUE THREAD

**Issue by alienself** [bnoazx005/tcpp#16]
I was excited to use this project, however conditions do not work.

`#define VIEW_ENABLED 1`

`#if VIEW_ENABLED && GLOBAL_ENABLED`: always return true even if only one of the term is defined
`#if VIEW_ENABLED > 10`: return true even though it shouldn't
`#if VIEW_ENABLED == 10`: return true even though it shouldn't

**Comment by bnoazx005** [comment]
Thanks for your feedback! 

Yeah, development of the project is still in progress. And I suppose that for now only **ifdef** and **ifndef** directives work well. But I'm going to fix this one in the near future
